# Configuration for automatic release notes generation
# Applies to both releases and pre-releases
# See: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - skip-changelog
      - duplicate
      - wontfix
      - invalid
    authors:
      - intothebeans
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - breaking
        - Semver-Major
    - title: New Features
      labels:
        - enhancement
        - feature
        - new-feature
        - Semver-Minor
    - title: Bug Fixes
      labels:
        - bug
        - fix
        - bugfix
        - Semver-Patch
    - title: Performance Improvements
      labels:
        - performance
        - perf
        - optimization
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Dependency Updates
      labels:
        - dependencies
        - deps
    - title: Other Changes
      labels:
        - "*"
